import {
  S3Client,
  HeadObjectCommand,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";

/**
 * Cloudflare R2 client, server-only. R2 exposes an S3-compatible API, so
 * the AWS SDK v3 S3Client works against it with a custom endpoint.
 * Credentials come from server-only env vars — this file must never be
 * imported from a Client Component or exposed to the browser bundle.
 */
function getR2Client(): S3Client {
  const accountId = process.env.R2_ACCOUNT_ID;
  const accessKeyId = process.env.R2_ACCESS_KEY_ID;
  const secretAccessKey = process.env.R2_SECRET_ACCESS_KEY;

  if (!accountId || !accessKeyId || !secretAccessKey) {
    throw new Error(
      "R2 credentials are not configured (R2_ACCOUNT_ID / R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY)."
    );
  }

  return new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId, secretAccessKey },
  });
}

function getBucketName(): string {
  const bucket = process.env.R2_BUCKET_NAME;
  if (!bucket) throw new Error("R2_BUCKET_NAME is not configured.");
  return bucket;
}

// Short-lived per the approved decision. PUT: long enough for a mobile
// upload to actually start; GET: re-issued fresh on every view rather
// than cached, so a leaked URL is useless within minutes.
const PRESIGNED_PUT_TTL_SECONDS = 300;
const PRESIGNED_GET_TTL_SECONDS = 300;

/**
 * The key is always server-generated by request_media_upload() — this
 * function never accepts or trusts a client-supplied key.
 */
export async function createPresignedUploadUrl(
  storageKey: string,
  contentType: string
): Promise<string> {
  const client = getR2Client();
  const command = new PutObjectCommand({
    Bucket: getBucketName(),
    Key: storageKey,
    ContentType: contentType,
  });
  return getSignedUrl(client, command, { expiresIn: PRESIGNED_PUT_TTL_SECONDS });
}

/**
 * Callers MUST re-run membership authorization (via the media SELECT RLS
 * boundary) immediately before calling this — this function performs no
 * authorization of its own. See media/queries.ts getMediaDownloadUrl.
 */
export async function createPresignedDownloadUrl(storageKey: string): Promise<string> {
  const client = getR2Client();
  const command = new GetObjectCommand({ Bucket: getBucketName(), Key: storageKey });
  return getSignedUrl(client, command, { expiresIn: PRESIGNED_GET_TTL_SECONDS });
}

/**
 * Verifies an uploaded object actually exists and returns R2's own
 * reported size — the only value confirm_media_upload() is allowed to
 * act on. Never trust a size reported by the browser.
 */
export async function headMediaObject(
  storageKey: string
): Promise<{ sizeBytes: number; contentType?: string } | null> {
  const client = getR2Client();
  try {
    const result = await client.send(
      new HeadObjectCommand({ Bucket: getBucketName(), Key: storageKey })
    );
    if (result.ContentLength == null) return null;
    return { sizeBytes: result.ContentLength, contentType: result.ContentType };
  } catch (err: unknown) {
    const name = typeof err === "object" && err !== null ? (err as { name?: string }).name : undefined;
    if (name === "NotFound") return null; // object genuinely isn't there yet
    throw err;
  }
}

/**
 * Best-effort only. DB-first deletion (approved decision) means the
 * database row is authoritative — an R2 failure here must never block or
 * roll back the DB operation that triggered it.
 */
export async function deleteMediaObjectBestEffort(storageKey: string): Promise<void> {
  try {
    const client = getR2Client();
    await client.send(new DeleteObjectCommand({ Bucket: getBucketName(), Key: storageKey }));
  } catch (err) {
    console.error("[storage] best-effort R2 delete failed", storageKey, err);
  }
}